config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :games, except: %i[create edit]

  resources :game_sessions, only: %i[index create show update] do
    resources :users, only: %i[create update], controller: 'game_sessions/users'
  end

  namespace :admin do
    root 'home#index'
    resources :games
    resources :users, only: %i[index show]
  end
end

app/models/game.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: games
#
#  id          :bigint(8)        not null, primary key
#  max_players :integer          not null
#  min_players :integer          not null
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_games_on_title  (title) UNIQUE
#

class Game < ApplicationRecord
  BOX_IMAGE_DIMENSIONS = { width: 450, height: 300 }.freeze

  validates :title, presence: true, uniqueness: true
  validates :min_players, presence: true
  validates :max_players, presence: true
  validates :max_players, numericality: {
    greater_than_or_equal_to: ->(game) { game.min_players },
    message: ->(game, _data) { "must be greater than or equal to min players (#{game.min_players})" }
  }

  # This destroys the join record, not the actual user
  has_many :ownerships, dependent: :destroy
  has_many :users, through: :ownerships
  has_many :game_sessions, dependent: :restrict_with_exception
  has_one_attached :box_image

  scope :by_title, -> { order(:title) }
  scope :random, ->(count) { order(Arel.sql('RANDOM()')).limit(count) }

  def box_image_thumbnail
    box_image.variant(resize_to_fit: [120, 80])
  end
end

app/controllers/admin/games_controller.rb
# frozen_string_literal: true

class Admin::GamesController < Admin::ApplicationController
  def index
    @games = Game.by_title
    @showcase_games = Game.with_attached_box_image.random(4)
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new(game_params)

    # TODO: Validate the uploaded image is not larger than 16k x 16k (Max size imagemagick will
    # handle by default)
    if @game.save
      GenerateTextBoxImagePreview.call(@game)
      redirect_to [:admin, @game], notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to [:admin, @game], notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to admin_games_path, notice: 'Game was successfully destroyed.'
  end

  private

  def game_params
    params.require(:game).permit(:title, :min_players, :max_players, :box_image)
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :require_user!

  def index
    @games = current_user.games.by_title
  end

  def new
    @q = params[:q]

    partial_query = Game.all
    partial_query = partial_query.where(Game.arel_table[:title].matches("%#{@q}%")) if @q

    # Only return list games that the user doesn't already have
    @games = partial_query.where.not(id: current_user.game_ids).by_title
  end

  def show
    @game = Game.find(params[:id])
  end

  def update
    game = Game.find(params[:id])
    current_user.games << game
    redirect_to new_game_path, notice: "Added #{game.title} to your games"
  end

  def destroy
    current_user.games.destroy(params[:id])
    respond_to do |format|
      format.js   { @id = params[:id] }
      format.html { redirect_to games_path, notice: 'Game was successfully destroyed.' }
    end
  end
end

app/views/admin/games/_form.html.erb
<%= form_with(model: [:admin, game], local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :min_players %>
  <%= form.number_field :min_players %>

  <%= form.label :max_players %>
  <%= form.number_field :max_players %>

  <%= form.label :box_image %>
  <%= form.file_field :box_image %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/games/edit.html.erb
<h1>Editing <%= @game.title %></h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', [:admin, @game] %> |
<%= link_to 'Back', admin_games_path %>

app/views/admin/games/index.html.erb
<div class="banner banner-small banner-dark flex">
  <div class="m-auto">
    <div class="banner-title">Games</div>
    <%= link_to 'Add New Game', new_admin_game_path, class: %w[btn btn--ghost] %>
  </div>
</div>

<div class="p">
  <div class=" grid grid--4">
    <% @showcase_games.each do |game| %>
      <div class="card">
        <div class="media">
          <div class="media__figure">
            <%= image_tag game.box_image_thumbnail %>
          </div>
          <div class="media__body">
            <h5 class="mt-0"><%= game.title %></h5>
            <%= game.min_players %>-<%= game.max_players %> Players
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Players</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td><%= link_to game.title, [:admin, game] %></td>
          <td><%= game.min_players %>-<%= game.max_players %></td>
          <td><%= link_to 'Edit', [:edit, :admin, game] %></td>
          <td><%= link_to 'Destroy', [:admin, game], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', admin_games_path %>

app/views/admin/games/show.html.erb
<h1><%= @game.title %></h1>
<%= image_tag @game.box_image %>
<p>Players: <%= @game.min_players %>-<%= @game.max_players%></p>

<%= link_to 'Edit', edit_admin_game_path(@game) %> |
<%= link_to 'Back', admin_games_path %>