config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :games, except: %i[create edit]

  resources :game_sessions, only: %i[index create show update] do
    resources :users, only: %i[create update], controller: 'game_sessions/users'
  end

  namespace :admin do
    root 'home#index'
    resources :games
    resources :users, only: %i[index show]
  end
end

app/models/game_session.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: game_sessions
#
#  id           :bigint(8)        not null, primary key
#  scheduled_at :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  game_id      :bigint(8)
#
# Indexes
#
#  index_game_sessions_on_game_id       (game_id)
#  index_game_sessions_on_scheduled_at  (scheduled_at)
#
# Foreign Keys
#
#  fk_rails_...  (game_id => games.id)
#

class GameSession < ApplicationRecord
  belongs_to :game, optional: true
  has_many :invitations, dependent: :destroy
  has_many :users, through: :invitations
  has_many :games, through: :users

  scope :past,        -> { where('scheduled_at <= ?', Time.current) }
  scope :upcoming,    -> { where('scheduled_at >= ?', Time.current) }
  scope :unscheduled, -> { where(scheduled_at: nil) }

  def available_games
    # Return all distinct games which are owned by a user in this session
    games.distinct.by_title
  end

  def suitable_games
    available_games.where(suitable_query)
  end

  def unsuitable_games
    available_games.where.not(suitable_query)
  end

  def attending_users
    users.where(invitations: { rsvp: :attending })
  end

  def not_responded_users
    users.where(invitations: { rsvp: :not_responded })
  end

  def declined_users
    users.where(invitations: { rsvp: :declined })
  end

  private

  def suitable_query
    min_players_condition = Game.arel_table[:min_players].lteq(users.size)
    max_players_condition = Game.arel_table[:max_players].gteq(users.size)

    min_players_condition.and(max_players_condition)
  end
end

app/controllers/game_sessions/users_controller.rb
# frozen_string_literal: true

class GameSessions::UsersController < ApplicationController
  before_action :require_user!
  before_action :require_access!

  def create
    user = User.find_by!(email: user_params[:email])
    game_session.users << user

    redirect_to game_session
  end

  def update
    user = User.find(params[:id])
    invitation = Invitation.find_by!(user: user, game_session: game_session)
    invitation.update!(rsvp: user_params[:rsvp])
    redirect_to game_session
  end

  private

  def user_params
    params.require(:user).permit(:email, :rsvp)
  end

  def game_session
    return @game_session if defined?(@game_session)

    @game_session = GameSession.find(params[:game_session_id])
  end

  def require_access!
    game_session.users.exists?(current_user.id) || not_found
  end
end

app/controllers/game_sessions_controller.rb
# frozen_string_literal: true

class GameSessionsController < ApplicationController
  before_action :require_user!
  before_action :require_access!, except: %i[create index]

  def index
    @game_sessions = case params[:filter]
                     when 'past'     then current_user.past_game_sessions
                     when 'upcoming' then current_user.upcoming_game_sessions
                     when 'created'  then current_user.created_game_sessions
                     else current_user.game_sessions
                     end
  end

  def create
    game_session = CreateGameSession.call(creator: current_user)
    redirect_to game_session
  end

  def show
    @game_session = GameSession.find(params[:id])
    @current_user_invitation = @game_session.invitations.find_by(user: current_user)
  end

  def update
    game_session = GameSession.find(params[:id])
    # TODO: Validate that the submited game is suitable
    game_session.update(game_session_params)
    redirect_to game_session
  end

  private

  def require_access!
    current_user.game_sessions.exists?(params[:id]) || not_found
  end

  def game_session_params
    params.require(:game_session).permit(:game_id, :scheduled_at)
  end
end

app/helpers/game_session_helper.rb
# frozen_string_literal: true

module GameSessionHelper
  def past_game_sessions_path
    game_sessions_path(filter: 'past')
  end

  def upcoming_game_sessions_path
    game_sessions_path(filter: 'upcoming')
  end

  def created_game_sessions_path
    game_sessions_path(filter: 'created')
  end
end

app/views/game_sessions/_game_session.html.erb
<div>
  <%= link_to(
    "#{game_session.id} - #{scheduled_time_in_words(game_session.scheduled_at)}",
    game_session_path(game_session)
  ) %>
</div>

app/views/game_sessions/index.html.erb
<h1>Game sessions</h1>

<%= link_to 'All', game_sessions_path %>
<%= link_to 'Upcoming', upcoming_game_sessions_path %>
<%= link_to 'Past', past_game_sessions_path %>
<%= link_to 'Created', created_game_sessions_path %>

<ul>
  <%= render @game_sessions %>
</ul>

app/views/game_sessions/show.html.erb
<div class="banner-small flex">
  <div class="m-auto">
    <div class="banner-title">Create Session</div>
  </div>
</div>

<div class="card card-floating mx-auto mb">
  <% if @game_session.game || @game_session.scheduled_at %>
    <div class="card__header bg-success color-white text-center">
      <% if @game_session.game %>
        <div>Chosen game: <%= @game_session.game.title %></div>
      <% end %>
      <% if @game_session.scheduled_at %>
        <div>Scheduled at: <%= scheduled_time_in_words(@game_session.scheduled_at) %></div>
      <% end %>
    </div>
  <% end %>
  <div class="card__body">

    <%= form_with model: @game_session, method: :patch, local: true do |form| %>
      <div class="field">
        <div>
          <%= form.label :scheduled_at, 'Scheduled time' %>
        </div>
        <div class="input-group">
          <span class="input-group__content"> <%= form.datetime_field :scheduled_at, data: { flatpickr: true } %> </span>
          <span class="btn btn--secondary btn--small"> <%= form.submit 'Schedule' %> </span>
        </div>
      </div>
    <% end %>

    <div class="tabs">
      <ul class="flex">
        <li class="is-active" data-toggle="tab" data-target="invited">
          Invited
        </li>
        <li data-toggle="tab" data-target="attending">
          Attending
        </li>
        <li data-toggle="tab" data-target="declined">
          Declined
        </li>
      </ul>
    </div>

    <div class="tab-panel is-active" id="invited">
      <div class="tab-panel__body">
        <ul>
          <% @game_session.not_responded_users.each do |user| %>
            <li><%= user.email %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="tab-panel" id="attending">
      <div class="tab-panel__body">
        <ul>
          <% @game_session.attending_users.each do |user| %>
            <li><%= user.email %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="tab-panel" id="declined">
      <div class="tab-panel__body">
        <ul id="declined">
          <% @game_session.declined_users.each do |user| %>
            <li><%= user.email %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <%= form_with url: game_session_users_path(@game_session), scope: :user, method: :post, local: true do |form| %>
      <div class="field">
        <div>
          <%= form.label :email, 'Player email' %>
        </div>
        <div class="input-group">
          <span class="input-group__content"> <%= form.email_field :email  %> </span>
          <span class="btn btn--secondary btn--small"> <%= form.submit 'Add player' %> </span>
        </div>
      </div>
    <% end %>

    <div>
      <label class="flex">RSVP: <%= @current_user_invitation.rsvp.humanize %></label>
    </div>

    <div class="flex">
      <div class="btn flex-grow mr-small">
        <%= form_with url: game_session_user_path(@game_session, @current_user), scope: :user, method: :patch, local: true do |form| %>
          <%= form.hidden_field :rsvp, value: 'attending'  %>
          <%= form.submit 'Attend' %>
        <% end %>
      </div>

      <div class="btn flex-grow">
        <%= form_with url: game_session_user_path(@game_session, @current_user), scope: :user, method: :patch, local: true do |form| %>
          <%= form.hidden_field :rsvp, value: 'declined' %>
          <%= form.submit 'Decline' %>
        <% end %>
      </div>
    </div>

  <!-- Games where we have the right number of players -->
  <div class="mt">
    <label>Available games</label>
    <% if @game_session.suitable_games.any? %>
      <ul class="cards my-tiny mb">
        <% @game_session.suitable_games.each do |game| %>
          <%= form_with model: @game_session, method: :patch, local: true do |form| %>
            <%= form.hidden_field :game_id, value: game.id %>
            <li class="card is-selectable">
              <h3 class="mb-none">
                <%= game.title %>
              </h3>
              <span class="mt-auto"><%= form.submit 'Choose game' %></span>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <div class="card">TODO: Add an Empty State</div>
    <% end %>
  </div>

  <!--
    Games where:
      max_players is lower than the number of people invited
    or
      min_players is greater than the number of people invited
  -->
  <div class="mt">
    <label>Unavailable games</label>
    <% if @game_session.unsuitable_games.any? %>
      <ul class="cards my-tiny mb">
        <% @game_session.unsuitable_games.each do |game| %>
          <div class="card card-disabled">
            <li><%= game.title %></li>
          </div>
        <% end %>
      </ul>
    <% else %>
      <div class="card">TODO: Add an Empty State</div>
    <% end %>
  </div>
</div>