config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :games, except: %i[create edit]

  resources :game_sessions, only: %i[index create show update] do
    resources :users, only: %i[create update], controller: 'game_sessions/users'
  end

  namespace :admin do
    root 'home#index'
    resources :games
    resources :users, only: %i[index show]
  end
end

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="notification <%= key %>">
    <button class="delete">X</button>
    <%= value %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light" id="navbar">
  <% if user_signed_in? %>
  <div class="navbar__logo"><%= nav_link_to 'Home', root_path %></div>
  <input class="navbar__menu-btn" type="checkbox" id="navbar__menu-btn" />
  <label class="navbar__menu-icon" for="navbar__menu-btn"><span class="navicon"></span></label>
  <ul class="navbar__menu">
    <div class="navbar__left">
      <% if current_user.admin? %>
        <li class="navbar__item">
          <%= nav_link_to 'Admin panel', admin_root_path %>
        </li>
      <% end %>

      <li class="navbar__item">
        <%= nav_link_to 'Games', games_path %>
      </li>

      <li class="navbar__item">
        <%= nav_link_to 'Game sessions', game_sessions_path %>
      </li>
    </div>

    <div class="navbar__right">
      <li class="navbar__item">
        <%= nav_link_to current_user.email, edit_user_registration_path %>
      </li>
      
      <li class="navbar__item">
        <%= nav_link_to 'Sign out', destroy_user_session_path, method: :delete %>
      </li>
    </div>
  </ul>


  <% else %>
  <input class="navbar__menu-btn" type="checkbox" id="navbar__menu-btn" />
  <label class="navbar__menu-icon" for="navbar__menu-btn"><span class="navicon"></span></label>
  <ul class="navbar__menu">
    <div class="navbar__right">
      <li class="navbar__item">
        <%= nav_link_to 'Sign up', new_user_registration_path %>
      </li>

      <li class="navbar__item">
        <%= nav_link_to 'Log in', new_user_session_path %>
      </li>
    </div>
  </ul>

  <% end %>
</div>