config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :games, except: %i[create edit]

  resources :game_sessions, only: %i[index create show update] do
    resources :users, only: %i[create update], controller: 'game_sessions/users'
  end

  namespace :admin do
    root 'home#index'
    resources :games
    resources :users, only: %i[index show]
  end
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

class Admin::HomeController < Admin::ApplicationController
  def index; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @past_game_sessions     = past_game_sessions
    @upcoming_game_sessions = upcoming_game_sessions
    today = Time.current.beginning_of_day..Time.current.end_of_day
    @number_of_games_today = GameSession.where(scheduled_at: today).size
  end

  private

  def past_game_sessions
    return [] unless user_signed_in?

    current_user.past_game_sessions.limit(10).order(scheduled_at: :desc)
  end

  def upcoming_game_sessions
    return [] unless user_signed_in?

    current_user.upcoming_game_sessions.limit(10).order(scheduled_at: :asc)
  end
end

app/views/admin/home/index.html.erb
<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
</head>

<div class="banner banner-dark flex">
  <div class="m-auto">
    <div class="banner-title">Pendium</div>
    <div class="banner-subtitle">Welcome to the admin panel</div>
  </div>
</div>

<div class="p">
  <div class="grid grid--2">

    <div class="card h-200 ml-auto card-floating">
      <div class="card__body flex flex--column text-center">
        <%= link_to admin_games_path do %>
          <div class="square">
            <div class="card__icon"><i class="fas fa-dice"></i></div>
          </div>
          <div class="card__title">Manage games</div>
        <% end %>
      </div>
    </div>

    <div class="card h-200 mr-auto card-floating">
      <div class="card__body flex flex--column text-center">
        <%= link_to admin_users_path do %>
          <div class="square">
            <div class="card__icon"><i class="fas fa-users"></i></div>
          </div>
          <div class="card__title">Manage users</div>
        <% end %>
      </div>
    </div>

  </div>
</div>